pipeline {
  agent {
      label 'maven'
  }
  stages {
    //start stages
    
    
    stage('Promote Azure') {
      steps {
        script {
          openshift.withCluster() {
            openshift.tag("mapit:stage", "mapit:azure")
          }
        }
      }
    }
    stage('Create Azure') {
      when {
        expression {
          openshift.withCluster() {
            return !openshift.selector('dc', 'mapit-stage').exists()
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.newApp("mapit:azure", "--name=mapit-azure").narrow('svc').expose()
          }
        }
      }
    }
    
   //end of stages 
    
 }
