
pipeline {
  agent {
      label 'maven'
  }
  stages {
    //start stages
    
    
    stage('Tag Azure') {
      steps {
        script {
          openshift.withCluster() {
            openshift.tag("mapit:stage", "mapit:azure")
          }
        }
      }
    }
    
    stage('Promote to Azure') {
      steps {
        script {
          openshift.withCluster(){
              
            def maps = openshift.selector( 'dc', [ app: 'mapit-stage' ] )
            def objs = maps.objects( exportable:true )
            openshift.withCluster('insecure://azure.ck.osecloud.com:8443','') {
              openshift.withProject('dev'){
                //maps.delete( '--ignore-not-present' )
                openshift.create( objs )
                maps.related( 'pods' ).untilEach {
                     return it.object().status.phase == 'Running'
                }
              }
            }
            
          }
          //end of with cluster
        }
      }
    }
    
    
 }
 //end of stages 
}
